### PR TITLE
Change main project author to “the rss2email maintainers” and drop maintainer list in setup.py

### PR DESCRIPTION
**Pull request by Profpatsch**
Seems fitting if we move to a community-maintained project.

### CODE REVIEW

**Comment by Yannik** [comment]
I'd personally prefer to drop both the ever-growing AUTHORS file and __contributors__ altogether. Anyone can check the contributers in the git history.

**Comment by Profpatsch** [comment]
> Anyone can check the contributers in the git history.

That’s not exactly true, the git history was cut in 2012, so e.g. Aaron Swartz (RIP) would not even appear.

But we can drop one of the two and merge them.

**Comment by Yannik** [comment]
> > Anyone can check the contributers in the git history.
> 
> That’s not exactly true, the git history was cut in 2012, so e.g. Aaron Swartz (RIP) would not even appear.
> 
> But we can drop one of the two and merge them.

that sounds good to me.

**Comment by Profpatsch** [comment]
Ooooh, I have made another discovery: `AUTHORS` is generated by https://pypi.org/project/update-copyright/, and the original “source of truth” here comes from the hidden file `.update-copyright.conf`.

**Comment by Yannik** [comment]
Are you sure? Trevor W. King and Thiago Coutinho are in `AUTHORS` but not in `.update-copyright.conf`.

**Comment by Profpatsch** [comment]
Yeah, the package generates the authors from the git history of single files, and `authors-hacks` is only used for authors that are not recorded in the git history (which started later than that).

**Comment by Yannik** [comment]
ah, got it.

**Comment by Profpatsch** [comment]
Okay, I pushed the result of running the `update-copyright` scripts on the current repo.

**Comment by Yannik** [comment]
that looks good to me. however, do we really want 20-line contributors lists in each file (for example email.py)? I'd personally prefer to simply refer users to the AUTHORS file in the individual files.

**Comment by Profpatsch** [comment]
> that looks good to me. however, do we really want 20-line contributors lists in each file (for example email.py)? I'd personally prefer to simply refer users to the AUTHORS file in the individual files.

I haven’t thought about this yet, just updating the system put into place by wking. I’ll merge for now, let’s discuss this seperately.

**Pull request merged**
