### PR TITLE
fix: enable to debug the name of the feed that times-out

### LINKED ISSUE #51: timeout: print the name of the feed that times-out
In my dozens of feeds, one times-out:

    [ERROR] 60 second timeout exceeded

It would be great to know which one to remove or update the feed URL.

### PR DESCRIPTION
**Pull request by monperrus**
fix #51

### CODE REVIEW

**Comment by Ekleog** [comment]
Wouldn't it be slightly better with `_LOG.info` instead of `_LOG.warning`? (that would then be viewable using more `-V`)

**Comment by monperrus** [comment]
This is what I did in the first place, but `info` logs are not shown with the `-V` switch.

**Comment by Ekleog** [comment]
They should be shown with `-VV` (`-VVV` being for `_LOG.debug`) :)

**Comment by Profpatsch** [comment]
I’d print to stderr by default, without having to give a verbosity flag.

**Comment by Ekleog** [comment]
Agreed. OTOH I think it should be `_LOG.info` and the default verbosity should be set to `info`, that would give the same end-result but with proper code semantics :)

Also, it'd ideally require to change the CLI to allow reducing the log level (something like “quiet”).

What about landing this changed with `_LOG.info` that also bumps the default log level to `info`, and opening for later an issue to add a “quiet” argument for people who want only warnings and errors? (anyway, to me, the current default of do-not-display-warnings appear to be totally wrong)

**Comment by monperrus** [comment]
Changed to `info` log level and bumped the default log level to info

**Comment by Profpatsch** [comment]
Not `warning?

**Comment by Ekleog** [comment]
I guess `info` vs. `warning` as a default is a matter of preference -- I personally prefer `info`, with no strong opinion.

However, I've just noticed https://github.com/rss2email/rss2email/blob/master/rss2email/main.py#L152 ; which looks like it's not actually increasing the log level, but resetting it from 0 -- meaning `r2e -V` and `r2e` are, AFAIU, exactly the same thing with the current `warning` default.

So the fix might also be, instead of replacing `warning` with `info` as the default, to replace `ERROR` with `WARNING` in the `args.verbose` computation, so that the first `-V` actually has an effect. Does that sound good to you?

**Comment by monperrus** [comment]
> Does that sound good to you?

Yes. It's the first time I see arithmetic in log level: `_logging.ERROR - 10 * args.verbose` how does this work?

**Comment by Ekleog** [comment]
@monperrus It comes from https://docs.python.org/3/library/logging.html#levels / https://docs.python.org/3/library/logging.html#logging.Logger.setLevel ; python predefines logging levels as integers that just get named aliases :)

**Comment by Profpatsch** [comment]
So, should we merge?

**Comment by monperrus** [comment]
I'd say yes, it's the first milestone towards better logging.

**Comment by monperrus** [comment]
Thanks!

**Pull request merged**
