### PR TITLE
Add a way to override user configured FROM field in add command

### PR DESCRIPTION
**Pull request by soutade**
Add an optional --from-email argument to "add" command.
In combination with force_from configuration, this allows to override FROM sender email for a specific feed.
It's usefull to automatically classify feeds.

### CODE REVIEW

**Comment by Profpatsch** [comment]
Hm, now we have 

```
usage: rss2email add [-h] [--from-email FROM_EMAIL] name url [email]
```

So both `--from-email` and `email` are optional, but one is positional and the other is not.

**Comment by soutade** [comment]
Yes.
I think "--from-email" won't be used a lot compared to "email".
I can turn it positional by set it "from_email", but it doesn't look like other parameters schema.
From my point of view, I don't like optional positional argument, because they became mandatory when there are multiples arguments and you only want to set the last one.

**Comment by Ekleog** [comment]
@soutade I think that we either should not have this argument, or we should allow to set *every* config file parameter via arguments, for consistency, including future ones that are not defined yet. Something like `[--option NAME VAL]`. Ideally we'd remove the `[email]` positional parameter for the next breaking release.

Does that plan sound good to you?

**Comment by soutade** [comment]
Sure. It's better for coherency. So, I keep my patch in my own fork.

**Comment by Ekleog** [comment]
Done, thanks! Keeping this open so as to track this pending refactor of arguments.

**Comment by kaashif** [comment]
Hey @soutade, great idea for a feature, this is indeed very useful. I am working on the more general version of overriding config values on the command line in #61, which lets you do `r2e -s from <my-custom-from-address>` as well as doing that with any config key. We wouldn't have got the idea for this feature without this PR, so I can add your name to a commit if you'd like.

In any case, I'd prefer discussion to move there, since I think the more general solution (inspired by @Ekleog's comment) is an improvement.

**Comment by soutade** [comment]
Hello,

Sure, a more generic switch is preferable for this kind of feature. It'll
allow us to be flexible for the coming years and not have a tons of
specific options. I like it.
In the other case, it would be good to document all new available but
"hidden" features for newcomers.
You don't have to mention my name for this, github will remind me thanks to
issue #44. I may commit later some new nice features if found one :)

**Pull request closed without merging**
