### PR TITLE
Add inline-links option

### PR DESCRIPTION
**Pull request by alyssais**
I find the default output very difficult to read, because
of (potentially very long) URIs showing up in the middle of the text.

### CODE REVIEW

**Comment by auouymous** [comment]
I agree. I've been using an inline-links and wrap-links patch.

Any chance you could also add the wrap-links option? Not wrapping inline-links prevents the entire paragraph from being wrapped, but it becomes useful when inline-links is false, because wrapped links can be harder to select.

It would also fully solve https://github.com/rss2email/rss2email/issues/96.

**Comment by kaashif** [comment]
Thanks for this contribution, this would be a useful config option to have. One comment: instead of modifying the existing test 3.config and 3.expected, can you copy them and make the changes to a new test 5.config and 5.expected? The changes to the test output are fairly significant.

Other than that I think this is good to be merged if there are no objections from other maintainers.

**Comment by Ekleog** [comment]
@alyssais I've allowed myself to implement @kaashif 's suggestion myself, as it was a trivial-ish change (two `cp` and one `git checkout`). So this is now ready to merge, thank you for the PR!

**Comment by Ekleog** [comment]
Oh. Well, and as we all forgot about the changelog, I'll just update it in a follow-up commit :)

**Pull request merged**
