### PR TITLE
Fix opmlexport output file writing

### LINKED ISSUE #113: opmlexport does not work
The `opmlexport` command try to open the output file into read mode, cf. https://github.com/rss2email/rss2email/blob/master/rss2email/command.py#L178, and of course it cannot write into it after that or it fails because the file does not exist.

### PR DESCRIPTION
**Pull request by nikaro**
Fixes #113

### CODE REVIEW

**Comment by auouymous** [comment]
It should probably use "wb" since opmlimport uses "rb".

**Comment by nikaro** [comment]
It is writing a text based file, so AFAIK using binary mode is not useful. It does not prevent the export file to be imported. And if i used `wb` i should have rewrite all `write('...')` to `write(b'...')`, so a bigger diff.

But as you want, let me know if if must change it to `wb`.

**Comment by Ekleog** [comment]
Thank you for this PR! I also think it would be slightly better to use `wb`, as AFAIU there could be newline changes if `w` only and a few added `b` should not be a big deal :)

Would it be possible for you to also add a regression test, so that we can't miss it if `opmlexport` ever gets broken this bad again?

**Comment by nikaro** [comment]
It's done. Let me know if there is something else to do.

**Comment by Ekleog** [comment]
Looks great, thank you! :)

**Pull request merged**
