### PR TITLE
Don't rewrite config file when fetching feeds

### LINKED ISSUE #110: rss2email should probably not modify the configuration file upon `r2e run`
Modifying the configuration file upon `r2e run` means that the user allowed to run `r2e` must also be allowed to modify the configuration file.

In quite a few cases, the configuration file would legitimately be owned by `root`, and `r2e` would run under the `rss2email` user, ideally not being allowed to edit the configuration file.

### PR DESCRIPTION
**Pull request by duxovni**
I believe this fixes #110 , it's working fine on my system at least.

### CODE REVIEW

**Comment by auouymous** [comment]
LGTM and the config file is not being written to on each run.

**Review by amiryal — APPROVED** [review]

**Comment by Ekleog** [comment]
The idea of the change looks great to me but I'm not so sure about the implementation.

Would it be possible to, instead of adding a boolean parameter to `save()`, instead rename `_save_feeds` to `save_feeds` (thus “making it public”), and to change `save` to only save the configuration and rename it `save_config`? And then have each `.save()` call instead call explicitly either `save_config`, `save_feeds`, or both.

This way, the API stays cleaner and more maintainable.

Does that sound reasonable to you? :)

**Comment by duxovni** [comment]
That's a great idea, just pushed that change :)

**Comment by Ekleog** [comment]
Awesome, thank you! :D

**Pull request merged**
