### PR TITLE
Updated required Python version in README

### PR DESCRIPTION
**Pull request by jpalus**

### CODE REVIEW

**Review by amiryal — APPROVED** [review]
The `README.rst` change LGTM. As for `poetry.lock`, I don’t know the Right Way to effect changes in it, but it seems safe enough to edit by hand, to change `python-versions = ">=3.5"` to `python-versions = ">=3.6"` to match, no?

**Comment by jpalus** [comment]
Not sure if the question is to me or not :). Anyway I'm not using poetry myself but it looks like `python-versions = ">=3.5"` in poetry.lock refers to html2text dependency no?

**Comment by amiryal** [comment]
> it looks like `python-versions = ">=3.5"` in poetry.lock refers to html2text dependency no?

You are right, I was being too lazy with my `git grep`. Sorry for the noise!

**Comment by Ekleog** [comment]
LGTM, thank you! For the poetry.lock, I've just pushed a commit updating it, though AFAICT it shouldn't need a backport to release :)

**Pull request merged**
